weaks
prathmeshranaut/Group_A_TaxFilingSoftware pull request #59
Opened 2020-12-02 05:54 UTC by tirth31

Bug fixing with t2202,spouse and dependent

2020-12-02 17:14 UTC, prathmeshranaut requested changes

2020-12-02 17:14 UTC, prathmeshranaut commented on src/dependent_details.c
> +<<<<<<< HEAD
Fix this issue

2020-12-03 17:47 UTC, prathmeshranaut approved these changes

2020-12-03 20:40 UTC, shreya9898 approved these changes

2020-12-04 04:05 UTC, RagunathAnbarasu approved these changes
Looks good

2020-12-04 22:03 UTC, merged